# 1. ????? ???? ??????
# jdbc:postgresql://????:????/???_????
# ?? ????????? ??? ???? - postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# 2. ????? ? ?????? (??????? ?? ?????? ??? ????????? ??? ? Docker)
spring.datasource.username=postgres
spring.datasource.password=root

# 3. ??????? (Java-?????, ??????? ????? ???????? ? Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. ????????? Hibernate (JPA)
# update - ???????? "???? ??????? ??? - ??????. ???? ???? - ??????".
# ??? ?????! H2 ??????????? "create-drop" (?????? ??? ??? ??????).
spring.jpa.hibernate.ddl-auto=update

# 5. ??????? (????? Hibernate ???? ??????????? SQL ? Postgres)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 6. ?????????? SQL ? ??????? (??????? ??? ???????)
spring.jpa.show-sql=true

# ????????? Telegram
bot.name=dnfwus_bot
bot.token=8562291867:AAHNAEEkoqtscz-0qtR5YCPpkmPkixtxX1k